### ISSUE TITLE
Field group with buttons on Firefox

### ISSUE THREAD

**Issue by domicoeth** [citizensadvice/cab-ui#51]
The buttons are sitting larger than the field, and have space between them

**Comment by domicoeth** [comment]
This is an outstanding issue that is becoming more urgent.

### IE

<img width="294" alt="ie" src="https://cloud.githubusercontent.com/assets/4223115/14912328/4bf6224e-0df3-11e6-8b2e-53a5ffafdb4d.png">

### Firefox

<img width="311" alt="firefox" src="https://cloud.githubusercontent.com/assets/4223115/14912329/4c0afa98-0df3-11e6-96eb-691e770b0361.png">

### Edge

<img width="292" alt="edge" src="https://cloud.githubusercontent.com/assets/4223115/14912330/4c17fe32-0df3-11e6-994e-b9aab09ec1f3.png">

**Comment by eliothill** [comment]
FF specific style `input::-moz-focus-inner` make fields `width: 100%;` and use negative margin for buttons.
[Link to update](https://github.com/citizensadvice/cab-ui/commit/878efd9787da76e86cbd8371db96894846bc5025)
