### ISSUE TITLE
Footer padding

### ISSUE THREAD

**Issue by danieldevlewis** [citizensadvice/cab-ui#71]
The "About Citizens Advice section" of the footer has too much padding.  This is particularly noticeable on mobiles.

It is because `flex-row` in the old stylesheets had no padding, as it is just a container.  In the new stylesheets `flex-row` is defined twice and the second time it has been given padding.

This is also going to cause further issues with current designs of home and custom section index pages as they use `flex-row` a lot and expect it to have no padding.

**Comment by domicoeth** [comment]
I've removed the padding, but the grid needs a general look over. @mrdaniellewis sat down with me and explained how the grid does/should work
